# Trabalho Final - Disciplina de IA - PPGI - Unirio

* Bruce Notario
* Marcus Monteiro
* Patricia Santos

# Etapa 02 - Entendimento dos dados

In [3]:
from constantes import ARQUIVO_VOTACOES
import pandas as pd
import matplotlib.pyplot as plt

# ARQUIVO DE VOTAÇÕES

In [4]:
df_deputados = pd.read_csv(filepath_or_buffer=ARQUIVO_DEPUTADOS, sep=";")
df_votacoes = pd.read_csv(filepath_or_buffer=ARQUIVO_VOTACOES, sep=";")
df_votos = pd.read_csv(filepath_or_buffer=ARQUIVO_VOTOS, sep=";")

NameError: name 'ARQUIVO_DEPUTADOS' is not defined

In [ ]:
df_votacoes.head(3)

,id,uri,data,dataHoraRegistro,idOrgao,uriOrgao,siglaOrgao,idEvento,uriEvento,aprovacao,votosSim,votosNao,votosOutros,descricao,ultimaAberturaVotacao_dataHoraRegistro,ultimaAberturaVotacao_descricao,ultimaApresentacaoProposicao_dataHoraRegistro,ultimaApresentacaoProposicao_descricao,ultimaApresentacaoProposicao_idProposicao,ultimaApresentacaoProposicao_uriProposicao
0,2458405-38,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-02-04,2025-02-04T17:09:33,180,https://dadosabertos.camara.leg.br/api/v2/orga...,PLEN,75386,https://dadosabertos.camara.leg.br/api/v2/even...,1.0,0,0,0,"Aprovado, em apreciação preliminar, o Parecer ...",2025-02-04T16:59:58,Votação preliminar em turno único.,2024-12-19T22:01:09,"Apresentação da MSC n. 1100/2024 (Mensagem), p...",2481703,https://dadosabertos.camara.leg.br/api/v2/prop...
1,2458405-40,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-02-04,2025-02-04T17:11:15,180,https://dadosabertos.camara.leg.br/api/v2/orga...,PLEN,75386,https://dadosabertos.camara.leg.br/api/v2/even...,1.0,0,0,0,"Aprovada a Medida Provisória nº 1.257 de 2024,...",2025-02-04T17:09:43,"Votação, quanto ao mérito, em turno único.",2024-12-19T22:01:09,"Apresentação da MSC n. 1100/2024 (Mensagem), p...",2481703,https://dadosabertos.camara.leg.br/api/v2/prop...
2,2458405-42,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-02-04,2025-02-04T17:11:59,180,https://dadosabertos.camara.leg.br/api/v2/orga...,PLEN,75386,https://dadosabertos.camara.leg.br/api/v2/even...,1.0,0,0,0,Aprovada a Redação Final assinada pelo relator...,2025-02-04T17:11:42,Votação da Redação Final.,2024-12-19T22:01:09,"Apresentação da MSC n. 1100/2024 (Mensagem), p...",2481703,https://dadosabertos.camara.leg.br/api/v2/prop...

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13827 entries, 0 to 13826
Data columns (total 20 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   id                                             13827 non-null  str
 1   uri                                            13827 non-null  str
 2   data                                           13827 non-null  str
 3   dataHoraRegistro                               13760 non-null  str
 4   idOrgao                                        13827 non-null  int64
 5   uriOrgao                                       13827 non-null  str
 6   siglaOrgao                                     13827 non-null  str
 7   idEvento                                       13827 non-null  int64
 8   uriEvento                                      12330 non-null  str
 9   aprovacao                                      13720 non-null  float64
 10  votosSim                                       13827 non-null  int64
 11  votosNao                                       13827 non-null  int64
 12  votosOutros                                    13827 non-null  int64
 13  descricao                                      13827 non-null  str
 14  ultimaAberturaVotacao_dataHoraRegistro         1406 non-null   str
 15  ultimaAberturaVotacao_descricao                1406 non-null   str
 16  ultimaApresentacaoProposicao_dataHoraRegistro  6961 non-null   str
 17  ultimaApresentacaoProposicao_descricao         12475 non-null  str
 18  ultimaApresentacaoProposicao_idProposicao      13827 non-null  int64
 19  ultimaApresentacaoProposicao_uriProposicao     6608 non-null   str
dtypes: float64(1), int64(6), str(13)
memory usage: 2.1 MB

In [ ]:
df_votacoes.describe()

,idOrgao,idEvento,aprovacao,votosSim,votosNao,votosOutros,ultimaApresentacaoProposicao_idProposicao
count,13827.000000,13827.000000,13720.000000,13827.000000,13827.000000,13827.000000,1.382700e+04
mean,178943.843422,69804.113112,0.957580,7.361973,5.215882,0.083388,1.204655e+06
std,251687.362698,24378.230941,0.201552,45.173883,33.537352,1.182496,1.262955e+06
min,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,2003.000000,76215.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00
50%,2014.000000,77568.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00
75%,537480.000000,79730.000000,1.000000,0.000000,0.000000,0.000000,2.533688e+06
max,539822.000000,80835.000000,1.000000,493.000000,409.000000,70.000000,2.609799e+06