# Trabalho Final - Disciplina de IA - PPGI - Unirio

* Bruce Notario
* Marcus Monteiro
* Patricia Santos

# Etapa 02 - Entendimento dos dados

In [24]:
from constantes import ARQUIVO_VOTOS_DAS_VOTACOES
import pandas as pd

In [25]:
df = pd.read_csv(filepath_or_buffer=ARQUIVO_VOTOS_DAS_VOTACOES, sep=";")

In [26]:
df.head(3)

,idVotacao,uriVotacao,dataHoraVoto,voto,deputado_id,deputado_uri,deputado_nome,deputado_siglaPartido,deputado_uriPartido,deputado_siglaUf,deputado_idLegislatura,deputado_urlFoto
0,106701-223,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-05T12:41:17,Sim,204379,https://dadosabertos.camara.leg.br/api/v2/depu...,Acácio Favacho,MDB,https://dadosabertos.camara.leg.br/api/v2/part...,AP,57,https://www.camara.leg.br/internet/deputado/ba...
1,106701-223,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-05T12:31:16,Sim,220714,https://dadosabertos.camara.leg.br/api/v2/depu...,Adail Filho,REPUBLICANOS,https://dadosabertos.camara.leg.br/api/v2/part...,AM,57,https://www.camara.leg.br/internet/deputado/ba...
2,106701-223,https://dadosabertos.camara.leg.br/api/v2/vota...,2025-11-05T12:32:08,Sim,221328,https://dadosabertos.camara.leg.br/api/v2/depu...,Adilson Barroso,PL,https://dadosabertos.camara.leg.br/api/v2/part...,SP,57,https://www.camara.leg.br/internet/deputado/ba...

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 175067 entries, 0 to 175066
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   idVotacao               175067 non-null  str
 1   uriVotacao              175067 non-null  str
 2   dataHoraVoto            175067 non-null  str
 3   voto                    174646 non-null  str
 4   deputado_id             175067 non-null  int64
 5   deputado_uri            175067 non-null  str
 6   deputado_nome           175067 non-null  str
 7   deputado_siglaPartido   175067 non-null  str
 8   deputado_uriPartido     175067 non-null  str
 9   deputado_siglaUf        175067 non-null  str
 10  deputado_idLegislatura  175067 non-null  int64
 11  deputado_urlFoto        175067 non-null  str
dtypes: int64(2), str(10)
memory usage: 16.0 MB

**Fatos:**

- Praticamente todos os campos de votos são do tipo texto.
    
**Acões:**

- Se faz necessário converter a DATA/HORA do voto para datetime.

In [28]:
df.describe()

         deputado_id  deputado_idLegislatura
count  175067.000000                175067.0
mean   181925.054522                    57.0
std     49744.746606                     0.0
min     62881.000000                    57.0
25%    160592.000000                    57.0
50%    204460.000000                    57.0
75%    220598.000000                    57.0
max    234788.000000                    57.0

**Fatos:**

- Os campos numéricos são do tipo ID.
    
**Acões:**

- Nenhuma.

In [29]:
df.nunique()

idVotacao                    550
uriVotacao                   550
dataHoraVoto              100133
voto                           5
deputado_id                  551
deputado_uri                 551
deputado_nome                553
deputado_siglaPartido         20
deputado_uriPartido           22
deputado_siglaUf              27
deputado_idLegislatura         1
deputado_urlFoto             551
dtype: int64

**Fatos:**

- Existem 5 diferentes valores de voto;
- Há votos de todos os 27 estados;
- Todos os votos são de uma mesma legislatura (há somente uma no arquivo);
- Há 20 partidos diferentes representados nos votos.
    
**Acões:**

- Nenhuma.

In [30]:
df['voto'].unique()

<StringArray>
['Sim', 'Artigo 17', 'Não', 'Abstenção', 'Obstrução', nan]
Length: 6, dtype: str

**Fatos:**

- Os votos podem ser: 'Sim', 'Artigo 17', 'Não', 'Abstenção', 'Obstrução', nan
    
**Acões:**

- Precisamos pensar em como tratar 'Artigo 17', 'Abstenção', 'Obstrução' e nan.

In [31]:
df.isnull().sum()

idVotacao                   0
uriVotacao                  0
dataHoraVoto                0
voto                      421
deputado_id                 0
deputado_uri                0
deputado_nome               0
deputado_siglaPartido       0
deputado_uriPartido         0
deputado_siglaUf            0
deputado_idLegislatura      0
deputado_urlFoto            0
dtype: int64

**Fatos:**

- Os únicos dados null são dados de votos (há 421 votos registrados como null);
    
**Acões:**

- Precisamos tratar os valores null para os votos.

In [32]:
df.isna().sum()

idVotacao                   0
uriVotacao                  0
dataHoraVoto                0
voto                      421
deputado_id                 0
deputado_uri                0
deputado_nome               0
deputado_siglaPartido       0
deputado_uriPartido         0
deputado_siglaUf            0
deputado_idLegislatura      0
deputado_urlFoto            0
dtype: int64

**Fatos:**

- Os únicos dados na são dados de votos (há 421 votos registrados como na);
    
**Acões:**

- Precisamos tratar os valores na para os votos.