# Trabalho Final - Disciplina de IA - PPGI - Unirio

* Bruce Notario
* Marcus Monteiro
* Patricia Santos

# Etapa 02 - Entendimento dos dados

In [8]:
from constantes import ARQUIVO_VOTACOES, ARQUIVO_DEPUTADOS, ARQUIVO_VOTOS
import pandas as pd
import matplotlib.pyplot as plt

# ARQUIVO DE DEPUTADOS

In [9]:
df_deputados = pd.read_csv(filepath_or_buffer=ARQUIVO_DEPUTADOS, sep=";")
df_votacoes = pd.read_csv(filepath_or_buffer=ARQUIVO_VOTACOES, sep=";")
df_votos = pd.read_csv(filepath_or_buffer=ARQUIVO_VOTOS, sep=";")

In [10]:
df_deputados.head(3)

,uri,nome,idLegislaturaInicial,idLegislaturaFinal,nomeCivil,cpf,siglaSexo,urlRedeSocial,urlWebsite,dataNascimento,dataFalecimento,ufNascimento,municipioNascimento
0,https://dadosabertos.camara.leg.br/api/v2/depu...,Abilio Brunini,57,57,ABILIO JACQUES BRUNINI MOUMER,NaN,M,NaN,NaN,1984-01-31,NaN,MT,Cuiabá
1,https://dadosabertos.camara.leg.br/api/v2/depu...,Acácio Favacho,56,57,ACÁCIO DA SILVA FAVACHO NETO,NaN,M,"https://twitter.com/acaciofavacho, https://www...",NaN,1983-09-28,NaN,AP,Macapá
2,https://dadosabertos.camara.leg.br/api/v2/depu...,Adail Filho,57,57,ADAIL JOSÉ FIGUEIREDO PINHEIRO,NaN,M,"https://www.instagram.com/adailfilho/, https:/...",NaN,1992-02-16,NaN,AM,Manaus

In [11]:
df_deputados.info()

<class 'pandas.DataFrame'>
RangeIndex: 7889 entries, 0 to 7888
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   uri                   7889 non-null   str
 1   nome                  7889 non-null   str
 2   idLegislaturaInicial  7889 non-null   int64
 3   idLegislaturaFinal    7889 non-null   int64
 4   nomeCivil             7889 non-null   str
 5   cpf                   0 non-null      float64
 6   siglaSexo             7889 non-null   str
 7   urlRedeSocial         562 non-null    str
 8   urlWebsite            63 non-null     str
 9   dataNascimento        7002 non-null   str
 10  dataFalecimento       4358 non-null   str
 11  ufNascimento          6925 non-null   str
 12  municipioNascimento   6519 non-null   str
dtypes: float64(1), int64(2), str(10)
memory usage: 801.4 KB

In [12]:
df_deputados.describe()

       idLegislaturaInicial  idLegislaturaFinal  cpf
count           7889.000000         7889.000000  0.0
mean              38.312080           39.884650  NaN
std               15.292747           15.008623  NaN
min                1.000000            1.000000  NaN
25%               29.000000           32.000000  NaN
50%               42.000000           43.000000  NaN
75%               50.000000           52.000000  NaN
max               57.000000           57.000000  NaN